name: Deploy Frontend and Backend to EC2

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Show working directory and files (root)
        run: |
          pwd
          ls -l

      # Build Frontend
      - name: List frontend files
        run: |
          cd pictotextonline-web/ocr-web
          pwd
          ls -l
      - name: Build frontend
        run: |
          cd pictotextonline-web/ocr-web
          npm install
          npm run build

      # Build Backend
      - name: List backend files
        run: |
          cd pictotextonline-web/ocr-web-backend
          pwd
          ls -l
      - name: Build backend
        run: |
          cd pictotextonline-web/ocr-web-backend
          npm install

      # Copy Frontend build to EC2
      - name: Copy frontend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "pictotextonline-web/ocr-web/dist/*"
          target: "/home/ubuntu/PicToText-frontend"

      # Copy Backend to EC2
      - name: Copy backend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "pictotextonline-web/ocr-web-backend/*"
          target: "/home/ubuntu/PicToTextOnline"

      # SSH into EC2 and restart backend
      - name: Restart backend with PM2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/PicToTextOnline
            npm install --production
            pm2 restart PicToTextOnline || pm2 start index.js --name PicToTextOnline
