name: Deploy Frontend and Backend to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Show working directory and files (root)
        run: |
          pwd
          ls -la
          echo "Repository structure:"
          find . -type d -name "node_modules" -prune -o -type d -print | head -20

      # Build frontend
      - name: Build frontend
        run: |
          cd ${{ steps.paths.outputs.frontend_path }}
          pwd && ls -la
          npm install
          npm run build

      # Build backend
      - name: Build backend  
        run: |
          cd ${{ steps.paths.outputs.backend_path }}
          pwd && ls -la
          npm install

      # Set environment variables for paths
      - name: Set paths
        id: paths
        run: |
          if [ -d "ocr-web" ]; then
            echo "frontend_path=ocr-web" >> $GITHUB_OUTPUT
            echo "backend_path=ocr-web-backend" >> $GITHUB_OUTPUT
          elif [ -d "pictotextonline-web/ocr-web" ]; then
            echo "frontend_path=pictotextonline-web/ocr-web" >> $GITHUB_OUTPUT
            echo "backend_path=pictotextonline-web/ocr-web-backend" >> $GITHUB_OUTPUT
          else
            echo "Error: Could not find frontend/backend directories"
            exit 1
          fi

      # Copy Frontend build to EC2
      - name: Copy frontend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "${{ steps.paths.outputs.frontend_path }}/dist/*"
          target: "/home/ubuntu/PicToText-frontend"

      # Copy Backend to EC2
      - name: Copy backend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "${{ steps.paths.outputs.backend_path }}/*"
          target: "/home/ubuntu/PicToTextOnline"

      # SSH into EC2 and restart backend
      - name: Restart backend with PM2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/PicToTextOnline
            npm install --production
            pm2 restart PicToTextOnline || pm2 start index.js --name PicToTextOnline