name: Debug - Find Directory Structure

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug repository structure
        run: |
          echo "=== Current working directory ==="
          pwd
          
          echo "=== Files and directories in root ==="
          ls -la
          
          echo "=== All directories (max depth 3) ==="
          find . -maxdepth 3 -type d | grep -v .git | sort
          
          echo "=== All package.json files ==="
          find . -name "package.json" -type f
          
          echo "=== Looking for common frontend/backend patterns ==="
          find . -maxdepth 2 -type d | grep -iE "(web|frontend|client|ui|app|ocr)" | head -10
          find . -maxdepth 2 -type d | grep -iE "(backend|server|api)" | head -10
          
          echo "=== Contents of any package.json files ==="
          for pkg in $(find . -name "package.json" -type f); do
            echo "--- $pkg ---"
            head -20 "$pkg"
            echo ""
          done